const handler = async (m, { conn }) => {
  const canal = '120363420941524030@newsletter';

  // Tu código o contenido de texto enriquecido aquí
  const codigo = `
const yt = require('yt-search');

const handler = async (m, { conn, text }) => {
  if (!text) return m.reply("📌 Ingresa un título o link de YouTube.");
  const res = await yt(text);
  const video = res.videos[0];
  if (!video) return m.reply("❌ No se encontró el video.");
  await conn.sendMessage(m.chat, { audio: { url: video.url }, mimetype: 'audio/mpeg' }, { quoted: m });
};
`;

  await conn.sendMessage(canal, {
    document: { url: Buffer.from(codigo, 'utf-8') }, // contenido directo
    fileName: 'youtube-play.js',
    mimetype: 'application/x-javascript', // mimetype clave para que salga COPY
    caption: '*🌱 Code :* YouTube Play\n\n_𝘚𝘺𝘭𝘱𝘩𝘪𝘦𝘵𝘵𝘦\'𝘴 | αlρнα ν1_',
    fileLength: 999999999999,
    contextInfo: {
      externalAdReply: {
        showAdAttribution: true,
        mediaType: 2,
        title: 'YouTube Downloader',
        body: 'Generated by Mai 🌸',
        sourceUrl: '',
        thumbnailUrl: 'https://telegra.ph/file/6e2f04abf38c0b3dca830.jpg'
      }
    }
  });

  m.reply('✅ Enviado como documento con botón copiar');
};

handler.command = ['codecopy'];
handler.tags = ['tools'];
handler.help = ['codecopy'];

export default handler;